site_name: pyphetools

theme:
  name: "material"
  features:
    #- navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: white
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime


nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Developers:
    - For developers: 'developers.md'
    - HPOA files: 'developers/hpoa_editing.md'
  - User guide:
    - Introduction: 'user-guide/tutorial.md'
    - Data Entry Template: 'user-guide/template.md'
    - Jupyter notebook:
      - overview: "user-guide/jupyter.md"
      - Column mappers:
        - Choosing a column mapper: 'user-guide/choosing_column_mapper.md'
        - Simple column mapper: 'user-guide/simple_column_mapper.md'
        - Constant column mapper: 'user-guide/constant_column_mapper.md'
        - Option column mapper: 'user-guide/option_column_mapper.md'
        - Threshold column mapper: 'user-guide/threshold_column_mapper.md'
      - Variant column mapper: 'user-guide/variant_column_mapper.md'
      - Cohort encoder: 'user-guide/cohort_encoder.md'
      - Validation: 'user-guide/validation.md'
      - Visualization: 'user-guide/visualization.md'
  - API:
    - "overview": 'api/overview.md'
    - "creation":
      - overview: "api/creation.md"
      - AgeColumnMapper: "api/creation/age_column_mapper.md"
      - CaseEncoder: "api/creation/case_encoder.md"
      - CaseTemplateEncoder: "api/creation/case_template_encoder.md"
      - Citation:  "api/creation/citation.md"
      - CohortEncoder: "api/creation/cohort_encoder.md"
      - ColumnMapper: "api/creation/column_mapper.md"
      - ConstantColumnMapper: "api/creation/constant_column_mapper.md"
      - Disease: "api/creation/disease.md"
      - DiseaseIdColumnMapper: "api/creation/disease_id_column_mapper.md"
      - HgvsVariant: "api/creation/hgvs_variant.md"
      - HpoConceptRecognizer: "api/creation/hpo_cr.md"
      - HpoExactConceptRecognizer: "api/creation/hpo_exact_cr.md"
      - HpoParser: "api/creation/hpo_parser.md"
      - HpTerm: "api/creation/hp_term.md"
      - Individual: "api/creation/individual.md"
      - IsoAge: "api/creation/iso_age.md"
      - MetaData: "api/creation/metadata.md"
      - MixedCohortEncoder: "api/creation/mixed_cohort_encoder.md"
      - OptionColumnMapper: "api/creation/option_column_mapper.md"
      - SexColumnMapper: "api/creation/sex_column_mapper.md"
      - SimpleColumnMapper: "api/creation/simple_column_mapper.md"
      - SimpleColumnMapperGenerator: "api/creation/simple_column_mapper_generator.md"
      - StructuralVariant: "api/creation/structural_variant.md"
      - Thresholder: "api/creation/thresholder.md"
      - ThresholdedColumnMapper: "api/creation/thresholded_column_mapper.md"
      - VariantColumnMapper: "api/creation/variant_column_mapper.md"
      - Variant: "api/creation/variant.md"
      - VariantManager: "api/creation/variant_manager.md"
      - VariantValidator: "api/creation/variant_validator.md"
    - "validation":
      - "overview": "api/validation.md"
      - "CohortValidator": "api/validation/cohort_validator.md"
      - "ContentValidator": "api/validation/content_validator.md"
      - "OntologyQC": "api/validation/ontology_qc.md"
      - "ValidationResult": "api/validation/validation_result.md"
    - visualization:
      - overview: "api/visualization.md"
      - DetailedSupplTable:  "api/visualization/detailed_suppl_table.md"
      - HpoaTableCreator: "api/visualization/hpoa_table_creator.md"
      - OnsetCalculator: "api/visualization/onset_calculator.md"
      - PhenopacketIngestor: "api/visualization/phenopacket_ingestor.md"
      - PhenopacketTable: "api/visualization/phenopacket_table.md"
      - QcVisualizer: "api/visualization/qc_visualizer.md"

plugins:
  - social
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pnrobinson
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pnrobins
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/peter-n-robinson-b7833811/


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/pnrobinson"  target="_blank" rel="noopener">Peter N Robinson</a>

