# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
requires-python = ">=3.5"
license.file = "LICENSE"
build-backend = "setuptools.build_meta"
urls.homepage = "https://github.com/monarch-initiative/pyphetools"
urls.repository = "https://github.com/monarch-initiative/pyphetools.git"
urls.documentation = "https://github.com/monarch-initiative/pyphetools"
urls.bugtracker = "https://github.com/monarch-initiative/pyphetools/issues"

keywords = [
    "Global Alliance for Genomics and Health",
    "GA4GH Phenopacket Schema",
    "Human Phenotype Ontology",
    "GA4GH",
    "HPO"]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["notebooks", "test"]

[project]
name = "pyphetools"
version = "0.1.0"
description = "Generate GA4GH phenopackets from tabular data"
readme = "README.md"
authors = [{ name = "pyphetolls", email = "peter.robinson@jax.org" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: BSD 3-Clause License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["feed", "reader", "tutorial"]
dependencies = [
    "openpyxl",
    "pandas",
    "phenopackets",
    "requests"
]
requires-python = ">=3.6"

#[project.optional-dependencies]
#dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/monarch-initiative/pyphetools"

#[project.scripts]
# ... = "reader.__main__:main"