name: Sphinx Documentation
on:
  # runs with manual start from Actions tab
  workflow_dispatch:
  # runs on pushes
  push:
    branches: [  main, develop ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
        ref: ${{ github.ref }}

    - name: Set up Python 3.
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: install
      run:  pip install sphinx sphinx-rtd-theme sphinx-copybutton 

    - name: Build documentation.
      run: |
          ## Init the target folder. 
          # We will put all site documentation there.
          mkdir -p gh-pages
          touch gh-pages/.nojekyll

          git checkout main
          git fetch
          git pull
          ## Init the target folder.
          # We will put all site documentation there.
          mkdir -p gh-pages
          sphinx-apidoc --separate --module-first -d 4 -H "API reference" --follow-links -o docs/apidocs pyphetools
          cd docs
          make html
          mv _build/* ../gh-pages
          
  
    - name: Deploy documentation.
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        clean: true
        folder: gh-pages
