name: CI

on:
    push:
      branches: [ develop ]
    pull_request:
      branches: [ main, develop ]

jobs:
    build:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os: [ windows-latest, macOS-latest, ubuntu-latest ]

      steps:
        - uses: actions/checkout@v4

        - name: Initialize Python 3.10
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"

        - name: Install pyphetools
          run: |
            python3 -m pip install --editable .[test]

        - name: Run all tests
          run: |
            pytest
